apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocs-claim
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
